server:
  port: 8080

spring:
  application:
    name: api-cursos

  # Configuración de la Base de Datos en Memoria (H2)
  datasource:
    url: jdbc:h2:mem:cursosdb
    driverClassName: org.h2.Driver
    username: fer
    password: fer

  # Configuración de JPA y Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # ¡ESTA LÍNEA ES VITAL! Hace que el script data.sql corra DESPUÉS de crear las tablas
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  # Habilitar la consola web de H2
  h2:
    console:
      enabled: true
      path: /h2-console